#!/usr/bin/env python3
"""
Script 2 — Fine-Tune Llama-3.2-3B on SPC Dataset
==================================================
Uses Unsloth for efficient LoRA fine-tuning on the RTX 5080.
Reads: /output/spc-qa-pairs.jsonl  (generated by 1_extract_dataset.py)
Saves: /output/adapter/            (LoRA adapter in GGUF format, ~50-80MB)
       /output/checkpoints/        (training checkpoints, not committed to git)

The adapter file (spc-adapter-lora.gguf) is what gets committed to git
and pulled on the Jetson. The Jetson uses it alongside the base model.

Run from Docker:
  docker compose -f docker-compose.train.yml run --rm train

Hardware requirements:
  - NVIDIA RTX 5080 (16GB VRAM) — enough for 3B model with LoRA
  - 32GB system RAM — needed for data loading
  - ~10GB free disk (model download + checkpoints)
"""

import json
import sys
import os
from pathlib import Path

import yaml
import torch

# Unsloth MUST be imported before transformers/peft to apply all optimizations
from unsloth import FastLanguageModel, is_bfloat16_supported

# Live metrics emitter — writes /output/metrics.json every 5 seconds
sys.path.insert(0, str(Path(__file__).parent))
from training_monitor import MetricsCallback

# ── Load configuration ─────────────────────────────────────────────────────────
CONFIG_PATH = Path("/workspace/config/training_config.yaml")
if not CONFIG_PATH.exists():
    CONFIG_PATH = Path("config/training_config.yaml")

with open(CONFIG_PATH) as f:
    cfg = yaml.safe_load(f)

MODEL_NAME    = cfg["model"]["name"]
MAX_SEQ_LEN   = cfg["model"]["max_seq_length"]
OUTPUT_DIR    = Path(cfg["output"]["dir"])
ADAPTER_DIR   = Path(cfg["output"]["adapter_dir"])
GGUF_FILENAME = cfg["output"]["gguf_filename"]
DATASET_PATH  = Path(cfg["dataset"]["path"])
SYSTEM_PROMPT = cfg["system_prompt"].strip()

ADAPTER_DIR.mkdir(parents=True, exist_ok=True)
(OUTPUT_DIR / "checkpoints").mkdir(parents=True, exist_ok=True)

# ── Validate dataset ───────────────────────────────────────────────────────────
if not DATASET_PATH.exists():
    print(f"ERROR: Dataset not found at {DATASET_PATH}")
    print("Run step 1 first:")
    print("  docker compose -f docker-compose.train.yml run --rm extract")
    sys.exit(1)

with open(DATASET_PATH) as f:
    dataset_lines = [l.strip() for l in f if l.strip()]

print(f"\nDataset: {DATASET_PATH}")
print(f"Total training pairs: {len(dataset_lines)}")

if len(dataset_lines) < cfg["dataset"]["min_pairs"]:
    print(f"WARNING: Only {len(dataset_lines)} pairs found (minimum recommended: {cfg['dataset']['min_pairs']})")
    print("Training will proceed but the model may not improve significantly.")

# ── CUDA check ─────────────────────────────────────────────────────────────────
if not torch.cuda.is_available():
    print("ERROR: No CUDA GPU detected!")
    print("Make sure Docker is running with --gpus all or the deploy.resources configuration.")
    sys.exit(1)

gpu_name = torch.cuda.get_device_name(0)
gpu_mem  = torch.cuda.get_device_properties(0).total_memory / (1024**3)
print(f"\nGPU detected: {gpu_name} ({gpu_mem:.1f} GB)")
print(f"CUDA version: {torch.version.cuda}")

# ── Load model with Unsloth ────────────────────────────────────────────────────
print(f"\nLoading base model: {MODEL_NAME}")
print("(This will download ~6GB on first run — subsequent runs use cache)\n")

from pipeline_writer import write_step as _pipeline_step
_PIPELINE_FILE = Path("/output/pipeline.json")
_pipeline_step(_PIPELINE_FILE, "llm_download", "running",
               f"Downloading {MODEL_NAME} (~6 GB, cached after first run)...")

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_NAME,
    max_seq_length=MAX_SEQ_LEN,
    dtype=None,           # Auto-detect: bfloat16 on Ampere+, float16 on older
    load_in_4bit=cfg["model"]["load_in_4bit"],
)

# ── Apply LoRA ────────────────────────────────────────────────────────────────
_pipeline_step(_PIPELINE_FILE, "lora_apply", "running",
               f"{MODEL_NAME} loaded — injecting LoRA adapter layers...")
print("Applying LoRA adapters...")

model = FastLanguageModel.get_peft_model(
    model,
    r=cfg["lora"]["r"],
    target_modules=cfg["lora"]["target_modules"],
    lora_alpha=cfg["lora"]["alpha"],
    lora_dropout=cfg["lora"]["dropout"],
    bias="none",
    use_gradient_checkpointing="unsloth",  # Reduces VRAM usage significantly
    random_state=42,
)

_pipeline_step(_PIPELINE_FILE, "lora_apply", "done", "LoRA layers injected")
# Print trainable parameter count
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total     = sum(p.numel() for p in model.parameters())
print(f"Trainable parameters: {trainable:,} ({100*trainable/total:.2f}% of {total:,} total)")

# ── Format dataset in Llama-3 chat format ────────────────────────────────────
def format_llama3_prompt(instruction: str, output: str) -> str:
    """Format a Q&A pair in Llama-3 instruction format."""
    return (
        "<|begin_of_text|>"
        "<|start_header_id|>system<|end_header_id|>\n\n"
        f"{SYSTEM_PROMPT}\n"
        "<|eot_id|>"
        "<|start_header_id|>user<|end_header_id|>\n\n"
        f"{instruction}\n"
        "<|eot_id|>"
        "<|start_header_id|>assistant<|end_header_id|>\n\n"
        f"{output}\n"
        "<|eot_id|>"
    )


print("Formatting dataset...")
formatted_texts = []
for line in dataset_lines:
    try:
        pair = json.loads(line)
        text = format_llama3_prompt(pair["instruction"], pair["output"])
        formatted_texts.append({"text": text})
    except (json.JSONDecodeError, KeyError) as e:
        print(f"  Skipping malformed line: {e}")

print(f"Formatted {len(formatted_texts)} training examples.")

from datasets import Dataset
train_dataset = Dataset.from_list(formatted_texts)

# ── Training ──────────────────────────────────────────────────────────────────
from trl import SFTTrainer
from transformers import TrainingArguments

print(f"\nStarting training...")
print(f"  Epochs:     {cfg['training']['epochs']}")
print(f"  Batch size: {cfg['training']['batch_size']} × {cfg['training']['gradient_accumulation_steps']} = {cfg['training']['batch_size'] * cfg['training']['gradient_accumulation_steps']} effective")
print(f"  LR:         {cfg['training']['learning_rate']}")
print()

metrics_cb = MetricsCallback(
    output_dir=str(OUTPUT_DIR),
    dataset_pairs=len(formatted_texts),
)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=train_dataset,
    dataset_text_field="text",
    max_seq_length=MAX_SEQ_LEN,
    dataset_num_proc=2,
    packing=False,
    callbacks=[metrics_cb],
    args=TrainingArguments(
        per_device_train_batch_size=cfg["training"]["batch_size"],
        gradient_accumulation_steps=cfg["training"]["gradient_accumulation_steps"],
        warmup_steps=cfg["training"]["warmup_steps"],
        num_train_epochs=cfg["training"]["epochs"],
        learning_rate=cfg["training"]["learning_rate"],
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
        logging_steps=cfg["training"]["logging_steps"],
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="cosine",
        seed=42,
        output_dir=str(OUTPUT_DIR / "checkpoints"),
        save_strategy="no",      # Disable checkpointing — avoids TRL SFTConfig pickle bug
        report_to="none",         # Disable wandb/tensorboard
    ),
)

try:
    trainer_stats = trainer.train()
except Exception as e:
    _pipeline_step(_PIPELINE_FILE, "training", "error", str(e)[:120])
    raise

# Print training summary
print(f"\nTraining complete!")
print(f"  Total steps:    {trainer_stats.global_step}")
print(f"  Final loss:     {trainer_stats.training_loss:.4f}")
print(f"  Time:           {trainer_stats.metrics.get('train_runtime', 0)/60:.1f} minutes")

# ── Save LoRA adapter (safetensors format for git) ───────────────────────────
SAFETENSORS_DIR = ADAPTER_DIR / "safetensors"
SAFETENSORS_DIR.mkdir(parents=True, exist_ok=True)
print(f"\nSaving LoRA adapter (safetensors) to {SAFETENSORS_DIR}...")
model.save_pretrained(str(SAFETENSORS_DIR))
tokenizer.save_pretrained(str(SAFETENSORS_DIR))
print("  Saved.")

# ── Export merged model in GGUF format (for direct use on Jetson) ────────────
# Unsloth merges LoRA weights into the base model, then quantizes to q4_k_m (~1.8GB)
# The Jetson llama-server loads this single self-contained GGUF file
GGUF_PATH = str(ADAPTER_DIR / GGUF_FILENAME)
print(f"\nExporting GGUF LoRA adapter to {GGUF_PATH}...")
print("(This is the file that will be committed to git and pulled on the Jetson)")

model.save_pretrained_gguf(
    str(ADAPTER_DIR),
    tokenizer,
    quantization_method="q4_k_m",  # Merged model + 4-bit quantization — good balance for Jetson
)

# Unsloth saves GGUF to <output_dir>_gguf/ — search both locations
GGUF_SEARCH_DIRS = [ADAPTER_DIR, Path(str(ADAPTER_DIR) + "_gguf")]
gguf_files = []
for _d in GGUF_SEARCH_DIRS:
    gguf_files = list(_d.glob("*.gguf"))
    if gguf_files:
        break
if gguf_files:
    import shutil
    final_path = str(ADAPTER_DIR / GGUF_FILENAME)
    if gguf_files[0] != final_path:
        shutil.move(gguf_files[0], final_path)
    size_mb = Path(final_path).stat().st_size / (1024**2)
    print(f"  GGUF adapter saved: {final_path}")
    print(f"  File size: {size_mb:.1f} MB")
    _pipeline_step(_PIPELINE_FILE, "complete", "done",
                   f"{GGUF_FILENAME} · {size_mb:.1f} MB · ready to commit")
else:
    print("  WARNING: GGUF export may have failed. Check output/adapter/ for files.")
    _pipeline_step(_PIPELINE_FILE, "export_gguf", "error", "GGUF file not found")

# ── Final instructions ────────────────────────────────────────────────────────
print(f"""
{'='*60}
TRAINING COMPLETE — NEXT STEPS
{'='*60}

Files saved to output/adapter/:
  {GGUF_FILENAME}    ← commit this to git (~50-80 MB)
  safetensors/              ← also commit (backup adapter)

From this spc-training/ folder, run:

  git add output/adapter/
  git commit -m "feat(spc): trained SPC adapter v1 — {len(formatted_texts)} pairs"
  git push origin main

Then on the Jetson:

  git pull
  bash books/statistics-process-control/spc-training/scripts/3_deploy_jetson.sh

{'='*60}
""")
